### ISSUE TITLE
Success(And Possibly Error) Callback functions not firing - typeof check failing

### ISSUE THREAD

**Issue by matthewdaize** [kartik-v/bootstrap-tabs-x#15]
I am passing into the TabsX (v1.2.1) w/ bootstrap-tabs-x (v1.3.1):
```php
'pluginOptions' => [
    'enableCache' => false, // tried this with true with no difference
    'successCallback' => [
        '#tabN' => 'function (data, status, jqXHR) { alert("test message"); },'
    ],
],
```

Spent quite a but of time troubleshooting as I'm not very proficient with JS and found that the following is never true:
```javascript
if (cbSuccess && typeof cbSuccess === "function") {
```

I found the success event was fired but would fail at the check and never execute the callback. `typeof(cbSuccess)` resulted in `string` and not the `function` that it is expecting and as such would never fire. If I hardcode that same function as cbSuccess right before the function it is fired as expected.

Am I doing something wrong when passing the value through?

**Comment by kartik-v** [comment]
> Am I doing something wrong when passing the value through?

Yes you are doing this wrong. The callback values cannot be a string ... it must be a javascript function callback.

If you are sending this from TabsX extension in yii ... you must use JsExpression class to send a proper javascript expression instead of string. For example:

```php
'pluginOptions' => [
    'enableCache' => false, // tried this with true with no difference
    'successCallback' => [
        '#tabN' => new yii\web\JsExpression('function (data, status, jqXHR) { alert("test message"); },')
    ],
],
```
