### ISSUE TITLE
can you give a full example for ajax tabs

### ISSUE THREAD

**Issue by asoqa** [kartik-v/bootstrap-tabs-x#2]
I used the ajax tabs, but I don't know how to use the data to render context, for example:

```
view:
...
    $item['label'] = $type;
    $item['content'] = '';
    $item['linkOptions'] = ['data-url'=>\yii\helpers\Url::to(['/datamine/graph'])];
...
    echo TabsX::widget([
        'items'=>$this->params['items'],
        'position'=>TabsX::POS_LEFT,
        'bordered'=>true,
        'sideways'=>false,
        'encodeLabels'=>false
    ]);

controller:
return json_encode(['content2'=>'test']);
```

The context of the item display empty

**Comment by geoffreymwangian** [comment]
Am new to yii does the line [/datamine/graph] mean datamine controller and graph view or what does it mean?

**Comment by kartik-v** [comment]
Its `controller/action` ... refer [yii documentation](http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html#routes). Post yii related queries in yii forum.
