### ISSUE TITLE
Events after tab content is rendered?

### ISSUE THREAD

**Issue by MatthewDaize** [kartik-v/bootstrap-tabs-x#20]
Not sure if this is a possibility, but I am attempting to fire a JS call after content within a tab has become visible. The "click" event fires however the function is called immediately when the user clicks the tab, then the content loads negating any post-"shown" functionality.

Any suggestions?

**Comment by kartik-v** [comment]
Suppose you are using ajax tabs then you can use the [tabsX:success](http://plugins.krajee.com/tabs-x#tabs-x-event-success) event. Check the other events in the documentation based on your need.
