### ISSUE TITLE
Selected tab does not load until click

### ISSUE THREAD

**Issue by dvolonnino** [kartik-v/bootstrap-tabs-x#29]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X ] The issue still exists against the latest `master` branch of bootstrap-tabs-x.
- [ X ] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/tabs-x) and [demos](http://plugins.krajee.com/tabs-x/demo).
- [ X ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ X ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Set the active tab to ajax
2. Refresh the page

## Expected behavior and actual behavior

Tab doesn't make ajax call

The active tab should automatically load on page ready.

## Environment

Browsers

- [ X ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ X ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- bootstrap-tabs-x version:

## Isolating the problem

- [ X ] This bug happens [on the plugin demos page](http://plugins.krajee.com/tabs-x/demo)
- [ X ] The bug happens consistently across all tested browsers
- [ X ] This bug happens when using bootstrap-tabs-x without other plugins
- [ X ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by contactr2m** [comment]
This issue is still there with Version 1.3.2
