### ISSUE TITLE
Release and tag version 1.3.3 missing

### ISSUE THREAD

**Issue by sviluppo** [kartik-v/bootstrap-tabs-x#31]
Release and tag version 1.3.3 missing.
File are updated in the repositories but there is no way to get the most updated version through composer.

**Comment by Slamdunk** [comment]
Can confirm, there is no tag beyond 1.3.2.
Release commit https://github.com/kartik-v/bootstrap-tabs-x/commit/6eeac8de2aba01ddc24082d3d792ab056a9fcb07 has no tag.
