### ISSUE TITLE
Update styles for nested tabs

### ISSUE THREAD

**Issue by AndriySvirin** [kartik-v/bootstrap-tabs-x#33]
[bootstrap-tabs-x.patch.txt](https://github.com/kartik-v/bootstrap-tabs-x/files/2926291/bootstrap-tabs-x.patch.txt)

Simple patch to correct the scope.

**Comment by kartik-v** [comment]
Can you please submit a PR for this? Thanks.

**Comment by AndriySvirin** [comment]
@kartik-v thanks for answer. unfortunatelly i can not make pull reqests.
